### ISSUE TITLE
Between mixin bug

### ISSUE THREAD

**Issue by eliwilliamson** [mojotech/mo#19]
'between' mixin uses max-width/max-height twice – should be min-width/min-height then max-width/max-height.

cheers!

**Comment by eliwilliamson** [comment]
@mixin between($low, $high, $vertical: false) {
  @if $vertical {
    @media screen and (min-height: $low) and (max-height: $high) {
      @content
    }
  } @else {
    @media screen and (min-width: $low) and (max-width: $high) {
      @content;
    }
  }
}

what i did to fix the bug ^

**Comment by aesnyder** [comment]
nice, wanna submit a pr @eliwilliamson ?

**Comment by eliwilliamson** [comment]
would love to @aesnyder but don't have permission :(

**Comment by cpjolicoeur** [comment]
It's a public repo.  Anyone has permission to submit a PR

**Comment by mordecai174** [comment]
just fork it and make the fix and open the pr @eliwilliamson

**Comment by samccone** [comment]
Here is a nice article that github put together on how to do it @eliwilliamson 

https://help.github.com/articles/using-pull-requests/

If you are stuck I can help you through the process, thanks again for finding and reporting this bug :+1: :mans_shoe: :bug:

**Comment by samccone** [comment]
fixed in 0.4.0

thanks again @eliwilliamson
