### ISSUE TITLE
mo as an ember-cli addons

### ISSUE THREAD

**Issue by ryancoughlin** [mojotech/mo#22]
I could use this. 95% of the projects at thoughtbot use Ember. I never looked in to what it take to make one. 

Thoughts?

**Comment by samccone** [comment]
suree no idea how to set this up ha

**Comment by cpjolicoeur** [comment]
![](https://media.giphy.com/media/ZanWL0MNtv3y0/giphy.gif?response_id=5924a326ab2d126968dd7e0d)

**Comment by ryancoughlin** [comment]
Bye bye Ember 👋

**Comment by mordecai174** [comment]
I love seeing your name in my inbox.... 🤝

**Comment by ryancoughlin** [comment]
Bless your heart 🙏🏻

I'll never forget you

**Comment by ryancoughlin** [comment]
And Craig

**Comment by samccone** [comment]
🥇 champ

**Comment by markalfred** [comment]
Dream team up in this thread 💅

**Comment by ryancoughlin** [comment]
When do we start our next project?

**Comment by mordecai174** [comment]
as soon as Sam hijacks an API for us to build a marionette app around.

**Comment by mordecai174** [comment]
@samccone i'd like to buy you a nice gold watch.
